[project]
name = "forex-ai-trader-part2-2"
version = "0.1.0"
description = "Backtesting engine and dashboard for Forex AI Trader"
requires-python = ">=3.12"
dependencies = [
  "pandas>=2.3.0",
  "numpy>=2.3.1",
  "ta>=0.10.2",
  "streamlit>=1.28.0",
  "plotly>=5.17.0"
] 